swagger: "2.0"
info:
  description: "Multi-Agent Pathfinding for Autonome Palleløftere på Transitlagre"
  version: "1.0.0"
  title: "Planlægningssystem"
  #termsOfService: "http://swagger.io/terms/"
  contact:
    email: "dat2c1-18@student.aau.dk"
  #license:
  #  name: "Apache 2.0"
  #  url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "https://github.com/msan19/P2"
#basePath: "/v2"


schemes:
- "http"
paths:
  /warehouse:
    get:
      summary: "Get warehouse"
      description: ""
      operationId: "GetWarehouse"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Warehouse"
        500:
          description: "Warehouse info not yet received"
    post:
      summary: "Update system's graph for warehouse"
      description: ""
      operationId: "PostWarehouse"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "warehouse"
        #description: "Object for warehouse"
        required: true
        schema:
          $ref: "#/definitions/Warehouse"
      responses:
        200:
          description: "Success"
        400:
          description: "Invalid Warehouse"
        401:
          description: "Invalid Graph"
  /routes:
    get:
      summary: "Returns all locked routes"
      description: ""
      operationId: "GetRoutes"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/Route"

  /orders:
    get:
      summary: "Returns all queued orders"
      description: ""
      operationId: "GetOrders"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/Order"
    post:
      summary: "Add an order to the system"
      description: ""
      operationId: "AddOrder"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "order"
        description: "An order to be queued"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        200:
          description: "Success"
        400:
          description: "Invalid order"

  /orders/{guid}:
    get:
      summary: "Get details for a single order"
      description: ""
      operationId: "GetOrder"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "guid"
        type: "string"
        format: "URI-encoded"
        description: "URI-encoded identifier for the order"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Route"
        400:
          description: "Order not found"
  /forklifts:
    get:
      summary: "Returns all known forklifts"
      description: ""
      operationId: "GetForklifts"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/ForkliftInfo"
  /forklifts/{guid}:
    get:
      summary: "Get details for a single forklift"
      description: ""
      operationId: "GetForklift"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "guid"
        type: "string"
        format: "URI-encoded"
        description: "URI-encoded identifier for the forklift"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/ForkliftInfo"
        400:
          description: "Forklift not found"
    put:
      summary: "Forklift posts status to server"
      description: ""
      operationId: "PostForklift"
      consumes:
      - "application/json"
      parameters:
      - in: "path"
        name: "guid"
        type: "string"
        format: "URI-encoded"
        description: "URI-encoded identifier for the forklift"
        required: true
      - in: "body"
        name: "forklift"
        description: "ForkliftInfo object for warehouse"
        required: true
        schema:
          $ref: "#/definitions/ForkliftInfo"
      responses:
        200:
          description: "Success"
        400:
          description: "Invalid forklift"

  /forklifts/{guid}/initiate:
    post:
      summary: "Forklift connects to server"
      description: ""
      operationId: "InitiateForklift"
      consumes:
      - "application/json"
      parameters:
      - in: "path"
        name: "guid"
        type: "string"
        format: "URI-encoded"
        description: "URI-encoded ID unique for physical forklift"
        required: true
      - in: "body"
        name: "forklift"
        description: "Forklift details"
        required: true
        schema:
          $ref: "#/definitions/ForkliftInfo"
      responses:
        200:
          description: "Success"
        400:
          description: "Invalid forklift"
        401:
          description: "Forklift already initiated"

    
definitions:
  Vector2:
    type: "object"
    required:
      - "x"
      - "y"
    properties:
      x:
        type: "number"
        format: "decimal"
        example: 10
      y:
        type: "number"
        format: "decimal"
        example: 14.5
  Date:
    type: "number"
    format: "Miliseconds since 1970-01-01 00:00:00 UTC"
    example: "1584965558174"

  Vertex:
    type: "object"
    required:
      - "id"
      - "position"
    properties:
      id:
        type: "string"
        format: "{guid}"
        example: "{bfa72706-befb-41d7-9ffb-2ede77607eea}"
      label:
        type: "string"
        example: "Delivery"
      position:
        $ref: "#/definitions/Vector2"
      adjacentVertexIds: 
        type: "array"
        format: "Vertex {guid}"
        items: 
          type: "string"
        example: "['N1-1', 'N1-3']"
  Edge:
    type: "object"
    required:
      - "vertexId_1"
      - "vertexId_2"
    properties:
      vertexId_1: 
        type: "string"
        example: "{bfa72706-befb-41d7-9ffb-2ede77607eea}"
      vertexId_2: 
        type: "string"
        example: "{0a54192e-9117-40cc-8f97-0265fd590131}"
      label:
        type: "string"
        example: "Optional Label"
        
  Graph:
    type: "object"
    required:
    - "vertices"
    properties:
      vertices:
        type: "array"
        items:
          $ref: "#/definitions/Vertex"
      edges:
        type: "array"
        items:
          $ref: "#/definitions/Edge"

  Warehouse:
    type: "object"
    properties:
      graph:
        $ref: "#/definitions/Graph"
      forkliftMovementSpeed:
        type: "number"
        format: "Meters per second"
        example: "3.4"

  PalletInfo:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "string"
        format: "guid"
        description: "Unique identifier for the pallet"
        example: "{1751227a-e9b9-4d37-912f-cdbea5e6fe90}"

  ForkliftInfo:
    type: "object"
    required:
      - "guid"
    properties:
      guid:
        type: "string"
        #format: "guid"
        description: "ID unique to the physical forklift"
        example: "{e00af90a-6645-4be4-9153-bb1d6e44bbba}"
      batteryStatus:
        type: "integer"
        description: "Remaining battery capacity in percentage"
        example: 78
      position:
        $ref: "#/definitions/Vector2"
        description: "Physical location of forklift within warehouse"
        #Unfortunate limitation of OpenAPI prevents
        ###TODO: Should this be a node?
          ### If so, then how about when the forklift is moving between nodes?
      state:
        type: "string"
        description: ""
        enum:
          - "idle"
          - "hasOrder"
          - "charging"
          - "initiating"
      palletId:
        type: "string"
        description: "The ID of the pallet currently on the fork"

  Instruction:
    description: "Instruction for a forklift, used in routes"
    type: "object"
    required:
      - "type"
      - "vertexId"
      - "startTime"
    properties:
      type:
        type: "string"
        enum:
          - "move"
          - "unloadPallet"
          - "loadPallet"
          - "charge"
          - "wait"
          - "sendFeedback"
      vertexId:
        type: "string"
        format: "{guid}"
        example: "{bfa72706-befb-41d7-9ffb-2ede77607eea}"
      palletId:
        type: "string"
      startTime:
        #Description doesn't work, as $ref replaces everything at the same level of itself
        description: "Time for when the execution of the instruction begins"
        $ref: "#/definitions/Date"

  Route:
    type: "object"
    required:
      - "id"
      - "instructions"
    properties:
      id:
        type: "string"
      status:
        type: "string"
        enum:
          - "queued"
          - "inProgress"
          - "completed"
          - "failed"

      instructions:
        type: "array"
        items:
          $ref: "#/definitions/Instruction"

  Order:
    type: "object"
    required:
      - "id"
      - "type"
      - "time"
      - "timeType"
    properties:
      id: 
        type: "string"
      type:
        type: "string"
        enum:
          - "movePallet"
          - "moveForklift"
          - "charge"
      time: 
        $ref: "#/definitions/Date"
      timeType: 
        type: "string"
        enum: 
          - "start"
          - "end"
      forkliftId:
        type: "string"
      palletId:
        type: "string"
      startVertexId:
        type: "string"
        format: "{guid}"
        example: "{bfa72706-befb-41d7-9ffb-2ede77607eea}"
      endVertexId:
        type: "string"
        format: "{guid}"
        example: "{bfa72706-befb-41d7-9ffb-2ede77607eea}"

    
    

externalDocs:
  description: "Find out more about Swagger"
  url: "https://github.com/msan19/P2"